#!/bin/bash 
. ./env.sh

if [ -z $1 ]; then
	echo "Using default value $APPDOMAIN"
else
	APPDOMAIN=$1
fi

echo "Getting information about app domain $APPDOMAIN"

curl -s -u $USER:$PW $URL/appdomain?name=$APPDOMAIN  | xmllint --format -
 
/bin/echo ""
